site_name: jshiki

repo_url: https://github.com/adalinesimonian/jshiki
repo_name: adalinesimonian/jshiki
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2016 â€” 2025 Adaline Simonian

theme:
  name: material
  favicon: assets/favicon.png
  logo: assets/logo.svg
  font:
    text: Open Sans
    code: Ubuntu Mono
  custom_dir: docs-theme
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs

nav:
  - Home: index.md
  - User Guide:
      - Getting Started: user-guide/index.md
      - Accessing Data: user-guide/accessing-data.md
      - Limiting Syntax: user-guide/limiting-syntax.md
      - Rules: user-guide/rules.md
      - Security: user-guide/security.md
  - API Docs: api/

extra_css:
  - css/extra.css
  - css/home.css

watch:
  - docs
  - docs-theme

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/adalinesimonian/jshiki
      name: jshiki on GitHub

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.inlinehilite
